### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by darothen** [NCAR/ASAPPyTools#11]
In order to support up up-stream Python 3 conversions (NCAR/PyReshaper#26), ASAPPyTools would also need Python 3 compatibility.

**Comment by kmpaul** [comment]
@darothen I've taken some time today to update the ASAPPyTools to use Python 3.  ...I think.  All of my tests now work with Python3.6, as well as Python2.6 and Python2.7.

The new code is in the devel branch, if you are interested.  I'm going to test this with the PyReshaper once I've updated it to use Python 3, too.

**Comment by darothen** [comment]
Awesome! Please let me know if there is anything I can do to help. I don't have any code that explicitly relies on ASAPPyTools to test but I can lend a hand anywhere else.

**Comment by kmpaul** [comment]
Then I wouldn't worry about it.  Just if you are curious.  I have been implementing some feature requests for the PyReshaper recently, anyway, so it seemed like a pretty easy thing to try to add before the next release.
