### ISSUE TITLE
Can we use CircleCI for all testing?

### ISSUE THREAD

**Issue by kmpaul** [NCAR/ASAPPyTools#17]
Now that we have CircleCI enabled, I'm wondering if we can use CircleCI for everything...and drop TravisCI?

**Comment by kmpaul** [comment]
cc: @andersy005

**Comment by andersy005** [comment]
Yes, we can. CircleCI is my favorite :) 
To achieve this, we will need to define a new job in the config.yml

**Comment by andersy005** [comment]
I am thinking that we could probably put tests in a separate script that gets invoked from `config.yml`. Do you think this is worth the effort?

**Comment by kmpaul** [comment]
Maybe.  Since CircleCI can parallelize the different jobs, we might not need TravisCI.  And I've prefer just having one technology.  It's easier, but it's not something that needs to be done now.  I'm just looking for feedback.

**Comment by andersy005** [comment]
I concur with you on this. I haven't thought about the parallelization feature of the CI until now. And I think this is something we can take advantage of. Having one tool for all testing will make it easier for us to master it too.

**Comment by kmpaul** [comment]
It would also speed up the testing if we created a docker image for the project testing...one with all of the necessary conda packages installed.

**Comment by andersy005** [comment]
Creating our own docker image: something else I haven't thought of :) This is a great idea.

**Comment by kmpaul** [comment]
This is now done with the latest release.
