### ISSUE TITLE
simplecomm not working on cheyenne/casper

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/ASAPPyTools#22]
On Cheyenne:

Currently Loaded Modules:
  1) python/3.7.5   3) ncarenv/1.3           5) mpt/2.22       7) nco/4.7.9
  2) gnu/9.1.0      4) ncarcompilers/0.5.0   6) netcdf/4.7.3   8) ncl/6.6.2

I am running a [test of simplecomm](https://github.com/NCAR/CESM_postprocessing/blob/master/Tools/ration_test.py).
and get the following result:

Exception AttributeError: "'SimpleCommMPI' object has no attribute '_comm'" in <bound method SimpleCommMPI.__del__ of <asaptools.simplecomm.SimpleCommMPI object at 0x2ad80d103e90>> ignored
MPT ERROR: could not run executable.

**Comment by sherimickelson** [comment]
@jedwards4b Do you have mpi4py in your Python path?  You'll want to make sure that you have mpi4py (>=1.3) installed and in your Python path for the testing to work.

**Comment by jedwards4b** [comment]
mpi4py 3.0.3 is in the path but it turns out that I had to port the test to python3 which did solve the problem.
